name: mediamine-collection
services:
  mediamine-collection-broadcast-db:
    image: postgres:16.4
    container_name: mediamine-collection-broadcast-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: mediamine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - path: ./.env
        required: true
    volumes:
      - pgdata-collection-broadcast:/var/lib/postgresql/data
      # - ./setup/db:/docker-entrypoint-initdb.d/
    networks:
      - mediamine-network
    restart: always

  mediamine-collection-broadcast-rabbit:
    image: rabbitmq:3-management
    container_name: mediamine-collection-broadcast-rabbit
    hostname: mediamine-collection-broadcast-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - '15672:15672' # RabbitMQ management UI
      - '5672:5672' # RabbitMQ messaging port
    restart: unless-stopped

volumes:
  pgdata-collection-broadcast:

networks:
  mediamine-network:
    driver: bridge
